name: Deploy Flutter Web to Firebase on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2) Install dependencies required for Flutter
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils unzip

      # 3) Install Flutter (Version 3.19.6 to match Dart 3.6+)
      - name: Install Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.6-stable.tar.xz
          tar xf flutter_linux_3.19.6-stable.tar.xz
          echo "export PATH=$PWD/flutter/bin:$PATH" >> $GITHUB_ENV
          flutter --version  # Verify installation

      # 4) Enable Flutter Web
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # 5) Install dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # 6) Build Flutter Web with API keys
      - name: Build Flutter Web
        run: |
          flutter build web --release \
            --dart-define=TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }} \
            --dart-define=OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --dart-define=COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            --dart-define=MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}

      # 7) Deploy to Firebase Hosting (Live)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROPHETAI_E600F }}
          channelId: live
          projectId: prophetai-e600f
