name: Deploy Flutter Web to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Install Flutter 3.13.x manually
      - name: Install & Build Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils unzip

          # Download Flutter 3.13.8 (or latest stable) for Dart 3.13.x
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.8-stable.tar.xz
          tar xf flutter_linux_3.13.8-stable.tar.xz

          # Add Flutter to PATH
          export PATH="$PWD/flutter/bin:$PATH"

          # Verify Flutter version (should show 3.13.x)
          flutter --version

          # Install pub dependencies
          flutter pub get

          # Build Flutter Web with your secrets from GitHub
          flutter build web --release \
            --dart-define=TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }} \
            --dart-define=OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --dart-define=COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            --dart-define=MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}

      # 3) Deploy to Firebase Hosting (live channel)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROPHETAI_E600F }}
          channelId: live
          projectId: prophetai-e600f
