name: Deploy Flutter Web to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Install Flutter manually
      - name: Install Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils unzip
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.5-stable.tar.xz
          tar xf flutter_linux_3.10.5-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter doctor

      # 3) Install Flutter dependencies
      - name: Install Dependencies
        run: |
          flutter pub get

      # 4) Build Flutter Web with Dart defines for your secrets
      - name: Build Flutter Web
        run: |
          flutter build web --release \
            --dart-define=TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }} \
            --dart-define=OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --dart-define=COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            --dart-define=MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}

      # 5) Deploy to Firebase Hosting (production / live)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROPHETAI_E600F }}
          channelId: live
          projectId: prophetai-e600f
