name: Deploy Flutter Web to Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Install Flutter 3.29.0 & Build in One Step
      - name: Install & Build Flutter
        shell: bash
        run: |
          set -e  # Fail fast on any error

          # 1. System dependencies
          sudo apt-get update
          sudo apt-get install -y wget xz-utils unzip

          # 2. Download Flutter 3.29.0 (which should include Dart >=3.6.1)
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.0-stable.tar.xz
          tar xf flutter_linux_3.29.0-stable.tar.xz

          # 3. Add Flutter to PATH
          export PATH="$PWD/flutter/bin:$PATH"

          # 4. Verify Flutter version
          flutter --version

          # 5. Enable Flutter web
          flutter config --enable-web

          # 6. Install dependencies
          flutter pub get

          # 7. Build Flutter web with your secrets
          flutter build web --release \
            --dart-define=TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }} \
            --dart-define=OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --dart-define=COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            --dart-define=MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}

      # 3) Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROPHETAI_E600F }}
          channelId: live
          projectId: prophetai-e600f
